// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwdaarbl28k9L6S5wfm07NgD5uel6XLx4',
    appId: '1:867561010691:web:a76db5929ca3f5f32dc036',
    messagingSenderId: '867561010691',
    projectId: 'chat-3a0f6',
    authDomain: 'chat-3a0f6.firebaseapp.com',
    storageBucket: 'chat-3a0f6.appspot.com',
    measurementId: 'G-3V5H9KZC7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVpmCOdbAMFBjlPBs9DY4wpzin6Y9uBtQ',
    appId: '1:867561010691:android:ef145170b167d4b72dc036',
    messagingSenderId: '867561010691',
    projectId: 'chat-3a0f6',
    storageBucket: 'chat-3a0f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX2Tw_qMCxzRnQihnR-hES1ZPhWm5vDMk',
    appId: '1:867561010691:ios:415c08d3440ae1e22dc036',
    messagingSenderId: '867561010691',
    projectId: 'chat-3a0f6',
    storageBucket: 'chat-3a0f6.appspot.com',
    iosBundleId: 'com.example.verygoodcore.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX2Tw_qMCxzRnQihnR-hES1ZPhWm5vDMk',
    appId: '1:867561010691:ios:868bcec67b10ebec2dc036',
    messagingSenderId: '867561010691',
    projectId: 'chat-3a0f6',
    storageBucket: 'chat-3a0f6.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
